---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - starlingx-common-tox-pep8
        - starlingx-common-tox-linters
        - ha-tox-pylint
        - ha-tox-coverage
        - ha-tox-coverage-c
        - ha-tox-security
        - ha-tox-linters-trixie
        - ha-tox-pep8-trixie
        - ha-tox-pylint-trixie
        - ha-tox-coverage-trixie
        - ha-tox-coverage-c-trixie
        - ha-tox-bandit-trixie
    gate:
      jobs:
        - starlingx-common-tox-pep8
        - starlingx-common-tox-linters
        - ha-tox-pylint
        - ha-tox-coverage
        - ha-tox-coverage-c
        - ha-tox-security
        - ha-tox-linters-trixie
        - ha-tox-pep8-trixie
        - ha-tox-pylint-trixie
        - ha-tox-coverage-trixie
        - ha-tox-coverage-c-trixie
        - ha-tox-bandit-trixie
    post:
      jobs:
        - stx-ha-upload-git-mirror

- job:
    name: ha-tox-pylint
    parent: tox
    description: |
      Run pylint test for ha in python3
    nodeset: debian-bullseye
    vars:
      tox_envlist: pylint
- job:
    name: ha-tox-coverage
    parent: tox
    description: |
      Run all tests with coverage analysis for ha
    nodeset: debian-bullseye
    vars:
      tox_envlist: coverage
    post-run: tests/playbooks/upload-coverage-reports.yaml
- job:
    name: ha-tox-coverage-c
    parent: tox
    description: |
      Run C/C++ coverage analysis via gcov/lcov for ha
    nodeset: debian-bullseye
    vars:
      tox_envlist: coverage-c
    post-run: tests/playbooks/upload-coverage-reports.yaml
- job:
    name: ha-tox-security
    parent: tox
    description: |
      Run security analysis for ha
    nodeset: debian-bullseye
    vars:
      tox_envlist: security
    post-run: tests/playbooks/upload-security-reports.yaml
- job:
    name: ha-tox-pylint-trixie
    parent: openstack-tox-py313
    description: |
      Run pylint for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: pylint-trixie
- job:
    name: ha-tox-coverage-trixie
    parent: openstack-tox-py313
    description: |
      Run all tests with coverage analysis for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: coverage-trixie
    post-run: tests/playbooks/upload-coverage-reports.yaml
- job:
    name: ha-tox-bandit-trixie
    parent: openstack-tox-py313
    description: |
      Run security analysis with bandit for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: bandit-trixie
    post-run: tests/playbooks/upload-security-reports.yaml
- job:
    name: ha-tox-linters-trixie
    parent: openstack-tox-py313
    description: |
      Run linters for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: linters-trixie
      tox_inline_comments: false
- job:
    name: ha-tox-pep8-trixie
    parent: openstack-tox-py313
    description: |
      Run pep8 for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: pep8-trixie
- job:
    name: ha-tox-coverage-c-trixie
    parent: openstack-tox-py313
    description: |
      Run C/C++ coverage analysis for ha (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: coverage-c-trixie
    post-run: tests/playbooks/upload-coverage-reports.yaml
- job:
    name: stx-ha-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors opendev.org/starlingx/ha to github.com/starlingx/ha.git
    vars:
      git_mirror_repository: starlingx/ha
    secrets:
      - name: git_mirror_credentials
        secret: stx-ha-github-secret3
        pass-to-parent: true

- secret:
    name: stx-ha-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - H1a716CNjuSeCh5wmetxwUIlG/06p6k1a0npBCAw+bel3hgE/G71nrwic2BzZKheNiU4n
          w3fsWqgU17dDpCQnVLKsbWEZOa0Sfzn5REYHsxivcGUq03sDbp0++kJyDsiqOO3H5aFiT
          16QBrjs/ispCs2BidAxKWirdr2lSC3/rq7/WXmQUp/eTYhYGclSCbYVCP/izy9L7p/XQL
          qmft8QQa1J/WaSmn6KkgY5IZKu/EAM+yHUNK72xlEtvLxv7oQiStp1ufYv5W94eRmIJYL
          GoGsvv2bOfiSOuFpf3QHhLM/SFrtYlBtSySeq6mcyrMz8bA4OLNOkjqABiqFWa7/z55fW
          xxbJNuVTBYiy3mTpK9/f2CXmoHG3IBFLVWX7gX9vg5qxpeDLlvzhaZ9tXWgxOyRr+ETVM
          cccDADFLdf5cICGG7bUdaW645Kewrj0abQvK0QKLre34SJfGn0W/s6qcaTqI7rJxZ0BVM
          LZ7NhQLlsG7U2pE+WkGlON5wq7IIO2ipsVmYw9XSqPgXqfedFmc/rbZrZiVw2wCRd7FnK
          POW4My+fYSQkeL81p3cS4p7XdDLTL/9R3QikpqYYaFAPGIWxmhDuU6+4h55JVOZjoGkAj
          vmiPwk7qrF05I4cOt9FXcDNchd4FB4FsOsjnmvx958/zLxW7OoGZj3y2g6DfUg=
        - pR+sc/PID3FsfP/aq7Y0eL3VtN+o8FaeYH8TGl9/m0Sb5V+YaYufwTAb+A9QYAHG6n51r
          Rg6oFlSX4Nn5TBpIVKdh/IfzPWRluPTzmOnb2dvhmul/raqjZ3P/azIla7yvshF7HOQ0S
          AeSjxIhRHqL9pDnT4XmFqmF0jU7ULLUVAO3yDCRIYA8zjGpwdfWIVh3SCI9bu1Bcbi5iB
          unEtCASe8LEcP6DBnPwNDF37VjgOwo7qFg6rOH1xZZN499zig3caTm5i3KqIq0sPIYDP/
          ElSOgEJ2/G9piYXkCBP3F9J5tgANEmMGYSxHefBwshOjaSO9kZw4BhHlVh1iqyRmFhieH
          xMDKezHZ8bRJXTuzM0nROrJGdQFvj3iuAh4cISBRwoQ+LOerXK2W01gXN+pEY8zuekhqx
          nZ2qfYVEodkMrds0Z6AviwfDPfl5Tcw27LRdIBmVLvSOPLiwtzmN3Ba+VxqmMFumim+F8
          Bt6cq418ix3BwcAM7AYX+PD6cebwAoaA67c7wOpO+qTTz68vonnfAG8z3/OXmMjBudaV/
          7J1xsHFr9fHFXquxncV0H9prmAp1vPUcNwhYOwNYztJrTF32THJ2IL1+F/a83cgTNXb8D
          ebp2Y0SqbWjFVpyAC04D740ddLYpDU0T6wv35jPwyvFS/aW9cNlF9P9FUseziQ=
        - jxEk5wKZg4DYhnxTJ2oyj9EiTmsN1rkhU5sAKnPX9fAkPPwE+g9LPrA5vB7teGbE6+Ph8
          b5Mt07C10Og6LH8pHgt+dKuRe+2nNyGbLXG+1Gb+CKFjIVEnsKStQofqcd7II9vEomWoZ
          QDskqf6tx4oVZVghvPU+NiXz73VDwB0yR/cIhzunPJxCvLzpz67KC1PEDJ86s7pUIWzCU
          du0trCG7YgfDcTAoK5LNWoQedi7JQpe/+PnH7fC3PfDGcqFIKblXQTz0LxiKMU+e34rll
          W3HszS/JXujabh/YGKbi9YQdHZlWX0tvnoPomHlxcWzNu+FomC852IbI5YXLHb1tNpjiP
          c83ECCU97KNPUZTbgA9nn3UnovljIi+MWscHhaWm8h40Z91LEsH1SVJpwPn1pqGdD7h2K
          FHQ0kPrTagVcEWRlibd5DduupCBUywWTXP5WRP43aQYHI4OEzsKv/Oq/zDlnlACe7BSKk
          K+IJ8c+BE79DeAp0wDT8wUQRFr4RCpcx9l9xNKDEpZDAh18JthUGeK+R+qMJSiWdvhxPf
          e8zu7h3Kjpb29QJt3bu9hhXvJxLIMH0SRuyIMYs0dob/0rs8U18OssiKMPLVEM1AcSNEa
          GvvEx2+ZyZmGS7iVo2KLvOrnvJ3Ii/vmERbItIQFbkp7adVU3L6r35gLzkcNok=
        - XV+JwWREN1z9S9eRwgMbGs+Mnytk3MwyI4vaiiTBXbfhd/mDUw0YPYK+pINFkDYXsgedp
          5tf8VLjF5FAsWSc7WZJN070+JhRfT6+7MiRvPd2CqJx1TGHov8BF5FTMGF/p2XvdtgGYS
          v4TRzn/GmMf3Op1J+iLnN5QYkf7cD04qkUYOuRFTKUm7e3wEQZD7nYWCVWoYt55kD418P
          5F/JmR7v407TfDs+7EEzw2NODQMR4DO4+xHwmiyWjAumCMv4orS4rVd/41CwxpWH/tZRf
          XTeUXqKtjDbzxM61DyXOpuEMuid7US+ZCfXe1x+/REi0l8xkEza7nevSzMY5Cbxr5Ldnm
          UkW7W/74/uA+AfVm4jChUhj16+3RebGbrNnPMTYASwcsiRQOCdA3dhWZxJhamZLzxBH8U
          pN8vux2ncQAJGR3EaQPec4UV8pmA0JUF2G1uj0hGnVnfMAifujEWT0+E8blA7rIlVE00o
          8KVuZ78V+bN6Qo+2VPiMv3b21T0tlNCgDo4Ceq306gAa8ZRH7hQ3zXL+RtDFTDw2dUMdS
          n/qW+fIQS8KB/GDBXzUT6ZoGh81uydXX3wc3X+9YSert2VH5PQVR5Cr+2kpYBTOF0wjYe
          NB8mjROnBusBGKBEBRr4px13hIkJvxC7g+IJ253aNPZmB/JHWTizHcgdiBntNo=
        - Nv0sWXOIFQ7/CMcyUJrkJGGL3XLkFAP2d64o0PqRsnqNotxusjZbdrvEHlxWBHcBNuNEP
          aoFMJCqkqf+KJp0C+jQVkQap7dD36ZJ4a3JxMCQwnA4UyvlkOkxGiLQqSWGcNA1c3+hnS
          0g9b7sMXV2Co3kWwT4lXq0FEOx3IycDXfph3+FODesWcT3bXKJIAPoLHOUinQt7epGsSA
          zbMgih3thkEzdEtakrfRROBGAsYiEqEZ7Ila+5oxr5cFDf0DFXaUueXJcv45Z2EPDfjc1
          QBL5tm1/V+/w/YPdtkXSVkYMxlSlbSrHfzlNqzMvn19K8baJ1JM5DRFNqfLdCD8YnEAAz
          1z0c0UxtRRQ27mKwHzODu3j40wNxfYOaNeaQ69q6ueR/qsjEnKrOraTv8knim2sxrs6pD
          2d/CUAkWPQqtsuaM5jIciA/rcbDUdbPJhjzI03Taj9GPHh2iWY/WjBWQVd+4zGkooiTS8
          CUdcNRJcffNnBg+ISTadoep4Q/zSKiaSCNwB3yyK88T5NBiLO2oUN0eFPC4cbETeylZwp
          CEVgOj66aTRXG4YdqniOGDg70MOAHoc5VRH5XzPvQf8M2AP+DZnZVC1TquF1zT7BVoxTS
          Sqt8NS7PjyX7/grtU8O1rA02MdTyYqmm/aYDEJRn4W24BcSeenRFq0AtePwfFI=
        - DRb0xoKvhNBDNgFogpnnkX+uB/5mJ7/GNLW4QscWxpqU1QSgWKT02Aj36c4ohKjL4EgBn
          ndtCN3QGPHHxln/r/B53HDKrjD57SfRXOTjUqaA4dlwFvuIpyPDjDKy+QmFI3ViaeDqgN
          pTqLcWDySrciEhMmQelws66Qu3yxyPoht3zmu6wt1cOEwSkP+Vj9EGj4diLIdi/8CR2ts
          fL/6UpfS1f/+Ov/yPggqb/ofE2WjMq1xwXXf5DGPs0ZdPRjEwHxQtYRZxko/w+MZ06o+R
          NPkX04F2pso2aksY7adkc7u1tUV4r/KjbSku7Pmr2JLrT8IWrsg+u+gtlO1T1LxJyaTB7
          EieS69RoOl61Vm2HSr0cMLXucRx/hryioA/8lNy0KsqoBVetKix9417Qd5QAoLEJy2FWR
          j2SRpPcrm5+A6X6WrEoNLMJwnNBjHyO0G7GwJmvhZZaEkA1/3Fuxc1ltrq0o+YmVYXex5
          yxHlZs50YuUQInrmfa797sQe1dBpd+WcAUTptFzuObfCaBD2su1/IkYO0eHQG5R+OLMby
          fGVG/Pbd2wV/72iNxeC/a4+XCDibPxuABGiJyZW/aVrkK/TjB9BnNqeYp0a58uyyw8HTF
          6iAA69ookzv1VlnPiE/Z/0Wd9XkQEWCMQqc6geuuDPud/QgMZC7f/JVYzyYtFE=
        - rANF2zC5uI2bfdj9ldWqHf4WJKKi/8q7ivV5XKfKgWN8CXq14VKVdex9bFv5j18nIxuYO
          f8QfIfKEvVvK2Rx/94TvVUIkM30sHqZgp9vEyPyN+Wetl9RKZuyHk8o1s7p3h/S0/d4Yt
          FawdhmKTJkJSK3X9S6jDh24iRW20Msv4hvP60gnifX7KecYAqrDg+hK/AzwdjhuWdhikK
          6BLkLF1hWa+NPQWAPe3Mpd0bxrIp4hT568yw+C0CDNvJkFyW9GBl+eVHMGNtKw34kEBFR
          iaYwZAH5BHo29/4wf1cllQ4ZO8kUb6x8NjQaLnwo9zH9lSx8v9H78QNmhOpkpbOztMgsW
          B7rhilF15d0OW1DII7S+Yq9WwGtyoy46Mio7bLHfZhVjivuYEHvDpLpOIhVPbW4k+aPVt
          yNctVLJnQd7LrWUdg1nSVrd/eFuVXOssApOCMzyvBVobXklWxdWicI04U3A/TnvutFXsp
          msY9QWLwcSSCOaJot3SsVhd5H4YsqyKUG0B5NgdeIr8fUOPDGvtOaNrmfWuOkZ8DRLlzM
          Yd3/X6FwRw/B1pPo9QBd4j97d30TLnJ8mldVMj/yV3xpF/S1vuRE+OhxuGbJBFrzyVpWi
          WeNnuBqGLtJubdvBkxxsW+qGG+M9uCxHuKNYA94a7PJNgTmKibn+gtL9NijUik=
