#!/bin/bash
# Devstack settings

# Services
# sm-api
# sm-client
# sm-common
# sm-daemon
# sm-db
# sm-tools

# Defaults
# --------

STX_HA_NAME=ha

######### Plugin Specific ##########
enable_service $STX_HA_NAME

# This must not use any variables to work properly in the devstack playbook
define_plugin ha
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires ha metal
plugin_requires ha config

# Initial source of lib script
source $DEST/ha/devstack/lib/ha
